parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  sourceType: module
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - plugin:prettier/recommended
plugins:
  - prettier
  - '@typescript-eslint'
rules:
  yoda: [error, always, { onlyEquality: true, exceptRange: true }]
  no-use-before-define: [error, {"functions": false, "classes": false, "variables": false}]
  prettier/prettier: [error, {
    "singleQuote": true,
    "useTabs": true,
    "semi": false,
    "trailingComma": all,
  }]
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/explicit-function-return-type': off
